version: '3.9'

services:

  react:
    build: ./frontend
    restart: always
    ports:
      - '3001:80'
    networks:
      - react_network
  
  ruby:
    build: ./backend
    ports:
      - '3002:4567'
    restart: always
    networks:
      - react_network

networks:
  react_network: