apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: backend:latest
#        resources:
#          limits:
#            memory: "128Mi"
#            cpu: "500m"
        imagePullPolicy: Never
        ports:
        - containerPort: 4567
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - port: 4567
    nodePort: 30001
  type: NodePort
  externalIPs: 
    - 10.0.1.23