apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
spec:
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: myapp2
        image: frontend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        # envFrom:
        #   - configMapRef:
        #       name: myapp2
---
apiVersion: v1
kind: Service
metadata:
  name: myapp2
spec:
  selector:
    app: myapp2
  ports:
  - port: 3000
    nodePort: 30002
  type: NodePort
  externalIPs: 
    - 10.0.1.23